spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false

sentinel:
  eager: false
  transport:
    enabled: false

seata:
  enabled: false

management:
  health:
    nacos:
      enabled: false

logging:
  level:
    com.infra.template: DEBUG
